{ makeScript
, inputs
, ...
}:
let
  defaultOut = to: file: ext: "${to}${file}.${ext}";
  toFile = { ext, comment ? f: "", to ? "./", out ? defaultOut }: file: rec {
    inherit ext file to comment;
    content = builtins.toFile "${file}.${ext}" ''${comment file}${import (./. + "/${file}.nix")}'';
    hook = ''
      mkdir -p ${to}
      cp --no-preserve all ${content} ${out to file ext}
      ${inputs.nixpkgs.git}/bin/git add -f ${out to file ext}
    '';
  };
  comments = {
    md = f: "<!-- generated by ${f}.nix -->\n";
    yaml = f: "# generated by ${f}.nix \n";
    default = f: "";
  };
  README = toFile { ext = "md"; comment = comments.md; } "README";
  gh-actions = toFile
    {
      ext = "yaml";
      comment = comments.yaml;
      to = "./.github/workflows/";
    } "gh-actions";
in
makeScript {
  name = "bootstraping";
  entrypoint = ''
    ${README.hook}
    ${gh-actions.hook}
  '';
}
