jobs:
  name: update
  steps:
    - env:
        GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
        SLACK_BOT_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
        SLACK_BOT_TOKEN_GIT_ACTION: ${{ secrets.SLACK_BOT_TOKEN_GIT_ACTION }}
      name: notify devs
      run: nix-shell run 'm . /notifySlack'
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v13
        with:
          extra_nix_config: experimental-features = nix-command flakes
          install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
      - env:
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          SLACK_BOT_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
          SLACK_BOT_TOKEN_GIT_ACTION: ${{ secrets.SLACK_BOT_TOKEN_GIT_ACTION }}
        name: notify devs
        run: nix-shell run 'm . /notifySlack'
name: CI
'on':
  push:
    branches:
      - master
