jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: channel:nixos-unstable
      - env:
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          SLACK_BOT_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_GIT_ACTION }}
        name: Build
        run: nix develop --command gh-actions-notify-slack-build
      - name: Post Deploy
        run: nix develop --command gh-actions-notify-slack-post-deploy
"on":
  push:
    branches:
      - master
